# Generated by Django 3.1 on 2021-09-23 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0002_auto_20210923_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_tweet', to='twitter.tweet')),
                ('favorite_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_tweets',
            field=models.ManyToManyField(related_name='_user_favorite_tweets_+', through='twitter.FavoriteRelation', to='twitter.Tweet', verbose_name='お気に入りのツイート'),
        ),
    ]
