# Generated by Django 3.1 on 2021-09-26 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0003_auto_20210923_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favorite_tweets',
            field=models.ManyToManyField(related_name='aaa', through='twitter.FavoriteRelation', to='twitter.Tweet', verbose_name='お気に入りのツイート'),
        ),
        migrations.AddConstraint(
            model_name='favoriterelation',
            constraint=models.UniqueConstraint(fields=('favorite_user', 'favorite_tweet'), name='favorite_unique'),
        ),
    ]
