# Generated by Django 3.1 on 2021-09-26 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0004_auto_20210926_1127'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='followrelation',
            constraint=models.UniqueConstraint(fields=('follower', 'followee'), name='follow_unique'),
        ),
    ]
