# Generated by Django 3.1 on 2021-09-30 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0005_auto_20210926_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favorite_tweets',
            field=models.ManyToManyField(related_name='favorite_user', through='twitter.FavoriteRelation', to='twitter.Tweet', verbose_name='お気に入りのツイート'),
        ),
    ]
