# Generated by Django 3.1 on 2021-10-24 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0006_auto_20211001_0351'),
    ]

    operations = [
        migrations.CreateModel(
            name='TweetClosure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_length', models.IntegerField(verbose_name='ノードからの距離')),
                ('ancestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descendant_tweet', to='twitter.tweet')),
                ('descendant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ancestor_tweet', to='twitter.tweet')),
            ],
        ),
        migrations.AddConstraint(
            model_name='tweetclosure',
            constraint=models.UniqueConstraint(fields=('ancestor', 'descendant', 'path_length'), name='tweetclosure_unique'),
        ),
    ]
