# Generated by Django 3.1 on 2021-10-24 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0007_auto_20211024_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='ancestor_tweets',
            field=models.ManyToManyField(related_name='decsendant_user', through='twitter.TweetClosure', to='twitter.Tweet', verbose_name='先祖レコード'),
        ),
    ]
